import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, FileCode2, GitBranch, Brain, Zap, Shield, Sparkles, Github, Wand2, FileText, MessagesSquare } from "lucide-react";
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/useAuth";

export const Route = createFileRoute("/")({
  component: Landing,
  head: () => ({
    meta: [
      { title: "DocuMind AI — Generate Docs Instantly with AI" },
      { name: "description", content: "Upload code or paste a GitHub repo. DocuMind AI generates README, API docs, architecture insights, and improvement suggestions in seconds." },
    ],
  }),
});

function Landing() {
  const navigate = useNavigate();
  const { user } = useAuth();
  return (
    <div className="relative min-h-screen overflow-x-hidden">
      <Navbar />
      <main className="pt-32">
        {/* Hero */}
        <section className="mx-auto max-w-7xl px-6 pt-16 pb-32 text-center relative">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="inline-flex items-center gap-2 glass rounded-full px-4 py-1.5 text-xs text-muted-foreground mb-8"
          >
            <Sparkles className="size-3.5 text-primary" />
            Powered by Gemini · Built for developers
          </motion.div>

          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.1 }}
            className="text-5xl md:text-7xl font-bold tracking-tight leading-[1.05]"
          >
            Generate Docs <br />
            <span className="text-gradient">Instantly with AI</span>
          </motion.h1>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.2 }}
            className="mt-6 max-w-2xl mx-auto text-lg text-muted-foreground"
          >
            Upload any codebase or paste a GitHub link. Get a professional README, API docs,
            architecture insights, and improvement suggestions — in seconds.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, delay: 0.3 }}
            className="mt-10 flex flex-wrap items-center justify-center gap-3"
          >
            <Button
              size="lg"
              onClick={() => navigate({ to: user ? "/dashboard" : "/login", search: user ? undefined : ({ mode: "signup" } as never) })}
              className="bg-aurora text-primary-foreground hover:opacity-90 glow px-7 h-12 text-base"
            >
              {user ? "Open Dashboard" : "Start generating free"}
              <ArrowRight className="size-4" />
            </Button>
            <Button
              size="lg"
              variant="outline"
              className="glass h-12 px-7 text-base"
              asChild
            >
              <a href="#features"><Wand2 className="size-4" /> See what it does</a>
            </Button>
          </motion.div>

          {/* Floating preview card */}
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.9, delay: 0.5 }}
            className="mt-24 mx-auto max-w-5xl"
          >
            <div className="glass rounded-3xl p-2 ring-glow animate-pulse-glow">
              <div className="rounded-2xl bg-[oklch(0.1_0.02_270)] p-6 text-left font-mono text-sm overflow-hidden">
                <div className="flex items-center gap-2 mb-4">
                  <div className="size-3 rounded-full bg-destructive/70" />
                  <div className="size-3 rounded-full bg-yellow-500/70" />
                  <div className="size-3 rounded-full bg-green-500/70" />
                  <span className="ml-3 text-xs text-muted-foreground">README.md · generated by DocuMind AI</span>
                </div>
                <pre className="whitespace-pre-wrap text-[oklch(0.85_0.04_270)] leading-relaxed">
{`# 🌌 Stellar API
> Real-time geospatial event streaming for distributed clients

## ✨ Features
- WebSocket pub/sub with backpressure
- JWT auth · Redis-backed sessions
- 99.9% uptime · k6 load-tested

## 🚀 Quick Start
\`\`\`bash
pnpm install && pnpm dev
\`\`\`

## 📐 Architecture
Client ⇄ Gateway ⇄ Redis ⇄ Postgres`}
                </pre>
              </div>
            </div>
          </motion.div>
        </section>

        {/* Features */}
        <section id="features" className="mx-auto max-w-7xl px-6 py-24">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight">
              Everything a great <span className="text-gradient">README</span> needs.
            </h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              Nine deeply useful artifacts generated from a single upload.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {features.map((f, i) => (
              <motion.div
                key={f.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.05 }}
                className="glass rounded-2xl p-6 hover:bg-white/[0.04] transition group"
              >
                <div className="size-11 rounded-xl bg-aurora/20 grid place-items-center mb-4 group-hover:scale-110 transition">
                  <f.icon className="size-5 text-primary" />
                </div>
                <h3 className="text-lg font-semibold">{f.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* How it works */}
        <section id="how" className="mx-auto max-w-7xl px-6 py-24">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight">
              Three steps. <span className="text-gradient">Production docs.</span>
            </h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {steps.map((s, i) => (
              <div key={s.title} className="glass rounded-2xl p-6 relative">
                <div className="text-6xl font-bold text-gradient/30 absolute top-4 right-6 opacity-30">
                  0{i + 1}
                </div>
                <s.icon className="size-7 text-primary mb-4" />
                <h3 className="text-lg font-semibold">{s.title}</h3>
                <p className="mt-2 text-sm text-muted-foreground">{s.desc}</p>
              </div>
            ))}
          </div>
        </section>

        {/* CTA */}
        <section id="stack" className="mx-auto max-w-5xl px-6 py-32">
          <div className="glass rounded-3xl p-12 md:p-16 text-center ring-glow">
            <Sparkles className="size-10 text-primary mx-auto animate-float" />
            <h2 className="mt-6 text-4xl md:text-5xl font-bold tracking-tight">
              Ship docs at the <span className="text-gradient">speed of thought.</span>
            </h2>
            <p className="mt-4 text-muted-foreground max-w-xl mx-auto">
              Free to start. No credit card. Sign up and generate your first doc in 30 seconds.
            </p>
            <Button
              size="lg"
              onClick={() => navigate({ to: user ? "/dashboard" : "/login", search: user ? undefined : ({ mode: "signup" } as never) })}
              className="mt-8 bg-aurora text-primary-foreground hover:opacity-90 glow h-12 px-8"
            >
              {user ? "Open Dashboard" : "Create your free account"}
              <ArrowRight className="size-4" />
            </Button>
          </div>
        </section>

        <footer className="border-t border-border/40 py-10 text-center text-sm text-muted-foreground">
          <p>© {new Date().getFullYear()} DocuMind AI · Built with cosmic energy.</p>
        </footer>
      </main>
    </div>
  );
}

const features = [
  { icon: FileText, title: "Professional README", desc: "Polished, badge-rich markdown ready for your repository." },
  { icon: Brain, title: "AI Code Explanation", desc: "Functions, classes, and modules explained in plain English." },
  { icon: GitBranch, title: "GitHub Repo Analyzer", desc: "Paste a URL. We fetch, analyze, and document the whole project." },
  { icon: FileCode2, title: "API Documentation", desc: "Auto-detected endpoints with parameters and responses." },
  { icon: Zap, title: "Setup & Run Guide", desc: "Step-by-step install, env, and deploy instructions." },
  { icon: Shield, title: "Improvement Suggestions", desc: "Bugs, security smells, and refactor opportunities." },
  { icon: Sparkles, title: "Health Score", desc: "Quantified project health from architecture to docs." },
  { icon: MessagesSquare, title: "Interview Questions", desc: "8 AI-generated questions derived from the code." },
  { icon: Github, title: "Folder Architecture", desc: "Annotated structure tree explaining each directory." },
];

const steps = [
  { icon: GitBranch, title: "Upload or link", desc: "Drag-and-drop files, paste code, or drop in a GitHub URL." },
  { icon: Brain, title: "AI analyzes", desc: "Gemini reads your code structure and intent." },
  { icon: FileText, title: "Get production docs", desc: "Tabbed preview · copy · download as markdown." },
];
